config/routes.rb
Rails.application.routes.draw do
  get 'pages/Accueil', to: 'pages#Accueil'
  get 'pages/equipes', to: 'pages#equipes'
  get 'pages/contact', to: 'pages#contact'
  get 'pages/bienvenue', to: 'pages#bienvenue'
  get 'new', to: 'pages#new'

  get 'showAll', to: 'pages#showAll'

  get 'potins/:id', to: 'pages#show', as: 'potin'
  post 'potins', to: 'pages#create', as: 'create_potin'

 # Routes pour l'édition, la mise à jour et la suppression d'un potin
  get 'potins/:id/edit', to: 'pages#edit', as: 'edit_potin'
  patch 'potins/:id', to: 'pages#update', as: 'update_potin'
  delete 'potins/:id', to: 'pages#destroy', as: 'delete_potin'



  # Pour RESTful routes de potins
  resources :potins, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  get 'signup', to: 'user#new'
  post 'signup', to: 'user#create'
  
  get 'login', to: 'user#login_form'
  post 'login', to: 'user#login'
  delete 'logout', to: 'user#destroy'
  get 'logout', to: 'user#destroy'
  get 'profile', to: 'user#profile'

  resources :users, only: [:new, :create]

  root 'pages#Accueil'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users

    validates :name, presence: true
end

app/models/potin.rb
class Potin < ApplicationRecord
    belongs_to :user
    validates :author, presence: true, length: { minimum: 3, maximum: 14 }
    validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :potins

  before_save { self.email = email.downcase }
  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include UserHelper
end

app/controllers/city_controller.rb
class CityController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def Accueil
    @potins = Potin.all
  end

  def equipes
    # logique pour l'action equipes
  end

  def contact
  end

  def bienvenue
    @potins = Potin.all
  end

  def show
    @potin = Potin.find(params[:id])
  end

  def showAll
    @potins = Potin.all
  end
  
  def new
    @potin = Potin.new
  end

  def create
    @potin = Potin.new(potin_params)
    @potin.user = User.find_by(id: session[:user_id])
    if @potin.save
      redirect_to potin_path(@potin), notice: 'Potin was successfully created.'
    else
      render :new
    end
  end

  def edit
    @potin = Potin.find(params[:id])
  end

  def update
    @potin = Potin.find(params[:id])
    if @potin.update(potin_params)
      redirect_to pages_showAll_path, notice: 'Potin mis à jour avec succès.'
    else
      render :edit
    end
  end

  def destroy
    @potin = Potin.find(params[:id])
    if @potin.destroy
      redirect_to pages_showAll_path, notice: 'Potin was successfully deleted.'
    else
      redirect_to pages_showAll_path, alert: 'Unable to delete Potin.'
    end
  end

  private

  def potin_params
    params.require(:potin).permit(:author, :content)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :require_login, only: [:profile]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      cookies[:user_id] = { value: @user.id, expires: 1.hour.from_now }
      redirect_to profile_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def login
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      cookies[:user_id] = { value: user.id, expires: 1.hour.from_now }
      redirect_to profile_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'login_form'
    end
  end

  def destroy
    log_out
    cookies.delete(:user_id)
    redirect_to login_path
  end

  def profile
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:prenom, :nom, :description, :email, :age, :city_id, :password, :password_confirmation)
  end

  def require_login
    unless logged_in?
      flash[:danger] = "Veuillez vous connecter."
      redirect_to login_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_helper.rb
module UserHelper
    def log_in(user)
        session[:user_id] = user.id
      end
    
      def current_user
        @current_user ||= User.find_by(id: session[:user_id])
      end
    
      def logged_in?
        !current_user.nil?
      end
    
      def log_out
        session.delete(:user_id)
        @current_user = nil
      end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheBigProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/Accueil.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="stylesheet" href="../assets/stylesheets/application.css">

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Potin</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Accueil</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="pages/bienvenue">Bienvenue</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="pages/equipes">Equipe</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="pages/contact">Contactez-nous</a>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Gossips
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="pages/new">Ajouter</a></li>
              <li><a class="dropdown-item" href="pages/showAll">Lister</a></li>
            </ul>
          </li>
        <% end %>
        <% if logged_in? %>
          <li><%= link_to "Se déconnecter", logout_path, method: :delete, class:"nav-link" %></li>
          <li><%= link_to "Profil", profile_path, class:"nav-link"  %></li> <!-- Lien ajouté vers la page de profil -->
        <% else %>
          <li><%= link_to "Se connecter", login_path, class:"nav-link"  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<% if logged_in? %>
   <h2>Bienvenue <%= User.find_by(id: session[:user_id]).prenom %> !</h2>
<% else %>
  <h2>Bienvenue a vous</h2>
<% end %>  

<p>Listes des potins</p>

<div class="potin1">
  <% @potins.each do |potin| %>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= potin.author %></h5>
        <p class="card-text"><%= potin.content %></p>
        <a href="<%= potin_path(potin) %>" class="btn btn-primary">Mon potin</a>
      </div>
    </div>
  <% end %>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

app/views/pages/bienvenue.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">


<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Potin</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="Accueil">Accueil</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Bienvenue</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="equipes">Equipe</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="contact">Contactez-nous</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Gossips
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="pages/new">Ajouter</a></li>
            <li><a class="dropdown-item" href="pages/showAll">Lister</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

<% @potins.each do |potin| %>
  <div class="potin">
    <h2>Bienvenue, <%= potin.author %>!</h2>
  </div>
<% end %>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

app/views/pages/contact.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">


<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Potin</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="Accueil">Accueil</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="bienvenue">Bienvenue</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="equipes">Equipe</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contactez-nous</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Gossips
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="pages/new">Ajouter</a></li>
            <li><a class="dropdown-item" href="pages/showAll">Lister</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>


<h1> Nous contacter</h1>

<p> 
  <ul>
    <li>E-mail: mansour@gmail.com</li>
    <li>Lieu: Yarakh</li>
    <li>site: potin.sn</li>
  </ul>
</p>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

app/views/pages/edit.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="stylesheet" href="../assets/stylesheets/application.css">


<h1>Éditer le Potin</h1>

<%= form_with model: @potin, url: potin_path(@potin), method: :patch, local: true do |form| %>
  <div class="field mb-3 w-25 m-auto pt-3">
    <%= form.label :author, 'Auteur', class: 'form-label' %>
    <%= form.text_field :author, class: 'form-control' %>
  </div>

  <div class="field mb-3 w-25 m-auto pt-3">
    <%= form.label :content, 'Contenu', class: 'form-label' %>
    <%= form.text_area :content, class: 'form-control', rows: 3 %>
  </div>

  <div class="actions w-25 m-auto">
    <%= form.submit 'Mettre à jour', class: 'btn btn-primary' %>
  </div>
<% end %>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

app/views/pages/equipes.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">


<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Potin</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="Accueil">Accueil</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="bienvenue">Bienvenue</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Equipe</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="contact">Contactez-nous</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Gossips
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="pages/new">Ajouter</a></li>
            <li><a class="dropdown-item" href="pages/showAll">Lister</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

<h1> Notre team</h1>

<p> 
  <ul>
    <li>Mbacke</li>
    <li>Mansour</li>
    <li>Aicha</li>
  </ul>
</p>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

app/views/pages/new.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">


<%= form_with model: @potin, url: create_potin_path, local: true do |form| %>
  <% if @potin.errors.any? %>
    <div id="error_explanation">
      <h2 class="alert alert-danger" role="alert"><%= pluralize(@potin.errors.count, "error") %> prohibited this potin from being saved:</h2>
      <ul>
        <% @potin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field mb-3 w-25 m-auto pt-3">
    <%= form.label :author, 'Auteur', class: 'form-label' %>
    <%= form.text_field :author, class: 'form-control', id: 'exampleFormControlInput1' %>
  </div>
  
  <div class="field mb-3 w-25 m-auto">
    <%= form.label :content, 'Contenu', class: 'form-label' %>
    <%= form.text_area :content, class: 'form-control', id: 'exampleFormControlTextarea1', rows: 3 %>
  </div>

  <div class="actions w-25 m-auto">
    <%= form.submit 'Valider', class: 'btn btn-primary' %>
  </div>
<% end %>



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

app/views/pages/show.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

<div class="d-flex"> 
  <% if @potin %>
    <div class="card m-4" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= @potin.author %></h5>
        <p class="card-text"><%= @potin.content %></p>
      </div>
    </div>
  <% else %>
  <p>Gossip non trouvé</p>
<% end %>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

app/views/pages/showAll.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
<link rel="stylesheet" href="../assets/stylesheets/application.css">



<p>Listes des potins</p>

<div class="potin1"> 
  <% @potins.each do |potin| %>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= potin.author %></h5>
        <p class="card-text"><%= potin.content %></p>
        <%= link_to '', edit_potin_path(potin), class: 'btn btn-success bi bi-pencil-square' %>
        <%= form_with url: delete_potin_path(potin), method: :delete, local: true do %>
           <button type="submit" class="btn btn-danger bi bi-trash3" data-confirm="Êtes-vous sûr ?"></button>
        <% end %>

      </div>
    </div>
  <% end %>
  
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

app/views/user/login_form.html.erb
<h1>Log in</h1>

<%= form_with(scope: :session, url: login_path, local: true) do |f| %>
  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>

<%= link_to "Sign up", signup_path %>

app/views/user/new.html.erb
<h1>Sign up</h1>

<%= form_with(model: @user, url: signup_path, local: true) do |f| %>
  <div class="field">
    <%= f.label :prenom %>
    <%= f.text_field :prenom, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :nom %>
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :city_id %>
    <%= f.collection_select :city_id, City.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/user/profile.html.erb
<h1>Profil</h1>
<p>Bienvenue, <%= @user.prenom %> <%= @user.nom %> !</p>
<p>Email : <%= @user.email %></p>
<p>Age : <%= @user.age %></p>
<p>Description : <%= @user.description %></p>